#!/bin/bash
#app=krissfeed

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a krissfeed
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Copy source files
final_path=/var/www/krissfeed
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/krissfeed.conf

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
sudo yunohost app setting krissfeed skipped_uris -v "/data/update.php"
